<?php
$product=$block->getProduct();
?>
<ul>
    <li>
        <span style="color: #000000;">You can get the product from our office&nbsp;</span>
    </li>

    <li>
        <span style="color: #000000;">Home delivery is also available&nbsp;</span>
    </li>

    <li>
        <span style="color: #000000;">
            <strong>You can get the product within 'three' working days after confirmation of the order by our customer care representative</strong>
        </span>
    </li>

    <li>
        <span style="color: #000000;">Delivery charge: Inside Dhaka-49 Taka, outside Dhaka-99 Taka&nbsp;</span>
    </li>

    <li>
        <span style="color: #000000;">You can pay online from your card or bKash, also you can pay cash to our office&nbsp;</span>
    </li>

    <li>
        <span style="color: #000000;">Once the product is purchased,it will not be refundable&nbsp;</span>
    </li>

    <li>
        <span style="color: #000000;">Your booking does not always guarantee product delivery&nbsp;</span>
    </li>

    <li>
        <span style="color: #000000;">Product delivery is entirely subjected to availability of stock&nbsp;</span>
    </li>


    <li>
        <span style="color: #000000;">Color of the products may slightly vary due to photography, lighting sources or your monitor setting/ PC resolution&nbsp;</span>
    </li>

    <li>
        <span style="color: #000000;">Product delivery may be interrupted or delayed due to natural disaster or incase of political unrest&nbsp;</span>
    </li>

    <li>
        <span style="color: #000000;">In case of delivery outside Dhaka, customers may have to collect certain products from the nearby courier service office&nbsp;</span>
    </li>


    <li>
        <span style="color: #000000;">
            <strong>If the delivery location is outside of Dhaka city, advance payment is a requirement</strong>
        </span>
    </li>


    <li>
        <span style="color: #000000;">Stock is limited!&nbsp;</span>
    </li>







</ul>
