<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="pub/media/gemsclip/css/carousel.css">
    <link rel="stylesheet" href="pub/media/gemsclip/css/search.css">
    <!--favicon-->
    <link rel="shortcut icon" href="favicon.ico">
    <!--.favicon-->
    <!--font-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i,900,900i&display=swap"
          rel="stylesheet">
    <!--.font-->
    <!--font awesome -->
    <link href="pub/media/gemsclip/css/all.css" rel="stylesheet">
    <!--.font awesome -->
    <!--common style-->
    <link rel="stylesheet" href="pub/media/gemsclip/css/style.css">
    <!--.common style-->

    <title>Your everyday office needs | Gemsclip.com</title>
</head>
<body>
<!--header code goes here-->




<!--.main content-->
<!-- footer -->
<!--<footer>-->
<!--    <div class="container">-->
<!--        <div class="row">-->
<!--            <div class="col-md-4">-->
<!--                <ul class="list-group">-->
<!--                    <li class="list-group-item active">About us</li>-->
<!--                    <li class="list-group-item"><a href="#">About Gemsclip</a></li>-->
<!--                    <li class="list-group-item"><a href="#">Gemsclip Team</a></li>-->
<!--                    <li class="list-group-item"><a href="#">Career</a></li>-->
<!--                    <li class="list-group-item"><a href="#">Contact Us</a></li>-->
<!--                </ul>-->
<!--            </div>-->
<!--            <div class="col-md-4">-->
<!--                <ul class="list-group">-->
<!--                    <li class="list-group-item active"><a href="#">Support</a></li>-->
<!--                    <li class="list-group-item"><a href="#">Return Policy</a></li>-->
<!--                    <li class="list-group-item"><a href="#">Credit Policy</a></li>-->
<!--                    <li class="list-group-item"><a href="#">Terms & Conditions</a></li>-->
<!--                    <li class="list-group-item"><a href="#">Privacy Policy</a></li>-->
<!--                </ul>-->
<!--            </div>-->
<!--            <div class="col-md-4">-->
<!--                <ul class="list-group">-->
<!--                    <li class="list-group-item active">MEDIA</li>-->
<!--                    <li class="list-group-item"><a href="#">News</a></li>-->
<!--                    <li class="list-group-item"><a href="#">Publications</a></li>-->
<!--                    <li class="list-group-item active">Join Us On</li>-->
<!--                    <li class="list-group-item">-->
<!--                        <a href="#"><img src="pub/media/gemsclip/img/fb-icon.png" alt="Facebook"></a>-->
<!--                        <a href="#"><img src="pub/media/gemsclip/img/twitter-icon.png" alt="twitter"></a>-->
<!--                        <a href="#"><img src="pub/media/gemsclip/img/linkedin-icon.png" alt="linkedin"></a>-->
<!--                    </li>-->
<!--                </ul>-->
<!--            </div>-->
<!--        </div>-->
<!--        <hr class="featurette-divider">-->
<!--        <p class="text-center">&copy; 2019 Gemsclip. All Rights Reserved.</p>-->
<!--    </div>-->
<!---->
<!--</footer>-->
<!--.footer-->
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

<!--<script src="pub/media/gemsclip/js/script.js"></script>-->


<script type="text/javascript">

    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
    });

    function mySearchFunction() {
        var x = document.getElementById("searchDIV");
        if (x.style.display === "block") {
            x.style.display = "none";
        } else {
            x.style.display = "block";
        }
    }
</script>




</body>
</html>