<!doctype html>
<html lang="en">

<body>

<!--header code goes here-->
<header>
    <nav class="navbar navbar-expand-md fixed-top bg-transparent">
        <a class="navbar-brand" href="#"><img src="<?=$block->getViewFileUrl("images/media/logo.png");?>" alt="logo"> </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#"><i class="fas fa-envelope"></i>Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fas fa-user"></i>Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="far fa-edit"></i>Become a member</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fas fa-shopping-cart"></i>Cart</a>
                </li>
            </ul>
        </div>
    </nav>
    <nav class="navbar navbar-expand-md fixed-top bg-transparent main-nav">
        <div class="collapse navbar-collapse" id="navbarCollapse1">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">ALL CATEGORIES</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">STATIONERY</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">CLEANING STUFF</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">PANTRY</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">IT & ELECTRONICS</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">SAFETY EQUIPMENT</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="far fa-heart"></i>My Product</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fas fa-search"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>
<!--.header code goes here-->
<!--main content-->
<main role="main">
    <!--hero area-->
    <div class="hero-area">
        <div id="myCarousel" class="carousel slide carousel-fade" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img   src="<?=$block->getViewFileUrl("images/media/slider-img-01.jpg");?>" alt="Slider Image" background="#777" color="#777" text=" "
                         title=" "/>
                    <div class="container">
                        <div class="carousel-caption">
                            <h1>One Stop Procurement Solution</h1>
                            <p>Can’t find an item you are looking for?<br>
                                Inform us to source it for you and we will do the rest.</p>
                            <p><a class="btn btn-lg btn-outline-success" href="#" role="button">Learn More</a></p>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <img   src="<?=$block->getViewFileUrl("images/media/slider-img-04.png");?>" alt="Slider Image" width="100%" height="100%"/>
                    <div class="container">
                        <div class="carousel-caption">
                            <h1>One Stop Procurement Solution</h1>
                            <p>Can’t find an item you are looking for?<br>
                                Inform us to source it for you and we will do the rest.</p>
                            <p><a class="btn btn-lg btn-outline-success" href="#" role="button">Learn more</a></p>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="<?=$block->getViewFileUrl("images/media/slider-img-03.png");?>" alt="Slider Image" width="100%" height="100%"/>
                    <div class="container">
                        <div class="carousel-caption">
                            <h1>One Stop Procurement Solution</h1>
                            <p>Can’t find an item you are looking for?<br>
                                Inform us to source it for you and we will do the rest.</p>
                            <p><a class="btn btn-lg btn-outline-success" href="#" role="button">Learn More</a></p>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="<?=$block->getViewFileUrl("images/media/slider-img-05.png");?>"  alt="Slider Image" width="100%" height="100%"/>
                    <div class="container">
                        <div class="carousel-caption">
                            <h1>One Stop Procurement Solution</h1>
                            <p>Can’t find an item you are looking for?<br>
                                Inform us to source it for you and we will do the rest.</p>
                            <p><a class="btn btn-lg btn-outline-success" href="#" role="button">Learn more</a></p>
                        </div>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <!--.hero area-->
    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->
    <!--how it works section-->
    <section class="how-it-works">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="heading-text text-center">
                        <h2>How It Works</h2>
                        <p>Learn how to use Gemsclip for buying your office needs!</p>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/zpOULjyy-n8?rel=0"
                                allowfullscreen></iframe>
                    </div>
                </div><!-- /.col-lg-4 -->
                <div class="col-lg-7">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <h5><span>01</span>Create an account</h5>
                            <p>Create an account to access your dashboard and manage your orders</p>
                        </li>
                        <li class="list-group-item">
                            <h5><span>02</span>Create your list</h5>
                            <p>Send your RFQ and add items to your list for easy order process</p>
                        </li>
                        <li class="list-group-item">
                            <h5><span>03</span>Place Order</h5>
                            <p>Place your order with customized delivery and billing information </p>
                        </li>
                        <li class="list-group-item">
                            <h5><span>04</span>Receive Delivery</h5>
                            <p>Receive order at your business location conveniently</p>
                        </li>
                    </ul>
                </div><!-- /.col-lg-4 -->
            </div><!-- /.row -->
        </div>
    </section>
    <!--.how it works section-->
    <!--Product Categories Section-->
    <section class="product-categories">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="heading-text text-center">
                        <h2>Product Categories</h2>
                        <p>Explore and list your desire product</p>
                    </div>
                </div>
                <div class="container my-4">
                    <!--Carousel Wrapper-->
                    <div id="multi-item-example" class="carousel slide carousel-multi-item" data-ride="carousel">

                        <!--Controls-->
                        <div class="controls-top">
                            <a class="btn-floating prev" href="#multi-item-example" data-slide="prev"><i
                                    class="fa fa-chevron-left"></i></a>
                            <a class="btn-floating next" href="#multi-item-example" data-slide="next"><i
                                    class="fa fa-chevron-right"></i></a>
                        </div>
                        <!--/.Controls-->

                        <!--Indicators-->
                        <ol class="carousel-indicators">
                            <li data-target="#multi-item-example" data-slide-to="0" class="active"></li>
                            <li data-target="#multi-item-example" data-slide-to="1"></li>
                            <li data-target="#multi-item-example" data-slide-to="2"></li>
                        </ol>
                        <!--/.Indicators-->

                        <!--Slides-->
                        <div class="carousel-inner no-black" role="listbox">

                            <!--First slide-->
                            <div class="carousel-item active">

                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                  src="<?=$block->getViewFileUrl("images/media/office-stationery-sample-img.png");?>"  alt="Office Stationary"
                                                 alt="Card image cap">
                                            <div class="card-body">
                                                <p class="numberofitems">240 Items</p>
                                                <h4 class="card-title">Office Stationery</h4>

                                                <a class="btn btn-view-all">View All</a>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-md-4 clearfix d-none d-md-block">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                  src="<?=$block->getViewFileUrl("images/media/cleaning-stuff-sample-img.png");?>"  alt="Cleaning Stuff"
                                                 alt="Card image cap">
                                            <div class="card-body">
                                                <p class="numberofitems">400 Items</p>
                                                <h4 class="card-title">Cleaning Stuff</h4>

                                                <a class="btn btn-view-all">View All</a>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-md-4 clearfix d-none d-md-block">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="<?=$block->getViewFileUrl("images/media/safety-equipment-sample-img.png");?>"  alt="Safety Equipment"
                                                 alt="Card image cap">
                                            <div class="card-body">
                                                <p class="numberofitems">200 Items</p>
                                                <h4 class="card-title">Safety Equipment</h4>

                                                <a class="btn btn-view-all">View All</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <!--/.First slide-->

                            <!--Second slide-->
                            <div class="carousel-item">

                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="<?=$block->getViewFileUrl("images/media/office-stationery-sample-img.png");?>"  alt="Office Stationary"
                                                 alt="Card image cap">
                                            <div class="card-body">
                                                <p class="numberofitems">240 Items</p>
                                                <h4 class="card-title">Office Stationery</h4>

                                                <a class="btn btn-view-all">View All</a>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-md-4 clearfix d-none d-md-block">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                   src="<?=$block->getViewFileUrl("images/media/cleaning-stuff-sample-img.png");?>"  alt="Cleaning Stuff"
                                                 alt="Card image cap">
                                            <div class="card-body">
                                                <p class="numberofitems">400 Items</p>
                                                <h4 class="card-title">Cleaning Stuff</h4>

                                                <a class="btn btn-view-all">View All</a>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-md-4 clearfix d-none d-md-block">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="<?=$block->getViewFileUrl("images/media/safety-equipment-sample-img.png");?>"  alt="Safety Equipment"
                                                 alt="Card image cap">
                                            <div class="card-body">
                                                <p class="numberofitems">200 Items</p>
                                                <h4 class="card-title">Safety Equipment</h4>

                                                <a class="btn btn-view-all">View All</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <!--/.Second slide-->

                            <!--Third slide-->
                            <div class="carousel-item">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                  src="<?=$block->getViewFileUrl("images/media/office-stationery-sample-img.png");?>"  alt="Office Stationary"
                                                 alt="Card image cap">
                                            <div class="card-body">
                                                <p class="numberofitems">240 Items</p>
                                                <h4 class="card-title">Office Stationery</h4>

                                                <a class="btn btn-view-all">View All</a>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-md-4 clearfix d-none d-md-block">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                  src="<?=$block->getViewFileUrl("images/media/cleaning-stuff-sample-img.png");?>"  alt="Cleaning Stuff"
                                                 alt="Card image cap">
                                            <div class="card-body">
                                                <p class="numberofitems">400 Items</p>
                                                <h4 class="card-title">Cleaning Stuff</h4>

                                                <a class="btn btn-view-all">View All</a>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-md-4 clearfix d-none d-md-block">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                             src="<?=$block->getViewFileUrl('images/media/safety-equipment-sample-img.png');?>"  alt="Safety Equipment"
                                                 alt="Card image cap">
                                            <div class="card-body">
                                                <p class="numberofitems">200 Items</p>
                                                <h4 class="card-title">Safety Equipment</h4>

                                                <a class="btn btn-view-all">View All</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!--/.Third slide-->
                        </div>
                        <!--/.Slides-->
                    </div>
                    <!--/.Carousel Wrapper-->
                </div>
            </div>
        </div>
    </section>
    <!--.Product Categories Section-->
    <!--Why Choose Us-->
    <section class="why-choose-us-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="heading-text text-center">
                        <h2>Why Choose Us</h2>
                        <p>Here are the reasons you can depend on Gemsclip</p>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="text-center">
                        <button type="button" class="btn tooltip-btn save-cost" data-toggle="tooltip" data-html="true"
                                title="Save procurement costs through discounted pricing, availing offers and many more">
                        </button>
                        <h5>Save Cost</h5>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="text-center">
                        <button type="button" class="btn tooltip-btn save-sourcing-time" data-toggle="tooltip"
                                data-html="true"
                                title="Save procurement costs through discounted pricing, availing offers and many more">
                        </button>
                        <h5>Save Sourcing Time</h5>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="text-center">
                        <button type="button" class="btn tooltip-btn one-stop" data-toggle="tooltip" data-html="true"
                                title="Save procurement costs through discounted pricing, availing offers and many more">
                        </button>
                        <h5>One Stop<br/>
                            Procurement Solution</h5>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="text-center">
                        <button type="button" class="btn tooltip-btn location-delivery" data-toggle="tooltip"
                                data-html="true"
                                title="Save procurement costs through discounted pricing, availing offers and many more">
                        </button>
                        <h5>On Location<br>
                            Delivery</h5>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="text-center">
                        <button type="button" class="btn tooltip-btn account-manager" data-toggle="tooltip"
                                data-html="true"
                                title="Save procurement costs through discounted pricing, availing offers and many more">
                        </button>
                        <h5>Account Manager<br>
                            Based Premium<br>
                            Service</h5>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="text-center">
                        <button type="button" class="btn tooltip-btn procurement-analytics" data-toggle="tooltip"
                                data-html="true"
                                title="Save procurement costs through discounted pricing, availing offers and many more">
                        </button>
                        <h5>Procurement<br>
                            Analytics</h5>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="text-center">
                        <button type="button" class="btn tooltip-btn authentic-products" data-toggle="tooltip"
                                data-html="true"
                                title="Save procurement costs through discounted pricing, availing offers and many more">
                        </button>
                        <h5>Authentic<br>
                            Products</h5>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="text-center">
                        <button type="button" class="btn tooltip-btn trusted-service" data-toggle="tooltip"
                                data-html="true"
                                title="Save procurement costs through discounted pricing, availing offers and many more">
                        </button>
                        <h5>Trusted<br>
                            Service</h5>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--.Why Choose Us-->
    <!--testimonials-->
    <section class="testimonials">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="heading-text text-center">
                        <h2>Testimonials</h2>
                        <p>Some kind words from clients about Gemsclip</p>
                    </div>
                    <div id="myCarousel2" class="carousel slide" data-ride="carousel">
                        <!-- Carousel indicators -->
                        <ol class="carousel-indicators">
                            <li data-target="#myCarousel2" data-slide-to="0" class="active"></li>
                            <li data-target="#myCarousel2" data-slide-to="1"></li>
                            <li data-target="#myCarousel2" data-slide-to="2"></li>
                        </ol>
                        <!-- Wrapper for carousel items -->
                        <div class="carousel-inner">
                            <div class="item carousel-item active">
                                <div class="img-box"><img  src="<?=$block->getViewFileUrl("images/media/user.png");?>"  alt=""></div>
                                <p class="testimonial">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu
                                    sem
                                    tempor, varius quam at, luctus dui. Mauris magna metus, dapibus nec turpis vel,
                                    semper
                                    malesuada ante. Idac bibendum scelerisque non non purus. Suspendisse varius nibh non
                                    aliquet.</p>
                                <p class="overview"><b>Paula Wilson</b><span
                                        class="company-name">CEO, Media Analyst</span></p>
                            </div>
                            <div class="item carousel-item">
                                <div class="img-box"><img  src="<?=$block->getViewFileUrl("images/media/user.png");?>"  alt=""></div>
                                <p class="testimonial">Vestibulum quis quam ut magna consequat faucibus. Pellentesque
                                    eget
                                    nisi a mi suscipit tincidunt. Utmtc tempus dictum risus. Pellentesque viverra
                                    sagittis
                                    quam at mattis. Suspendisse potenti. Aliquam sit amet gravida nibh, facilisis
                                    gravida
                                    odio.</p>
                                <p class="overview"><b>Antonio Moreno</b> <span
                                        class="company-name">CEO, Media Analyst</span></p>
                            </div>
                            <div class="item carousel-item">
                                <div class="img-box"><img  src="<?=$block->getViewFileUrl("images/media/user.png");?>"  alt=""></div>
                                <p class="testimonial">Phasellus vitae suscipit justo. Mauris pharetra feugiat ante id
                                    lacinia. Etiam faucibus mauris id tempor egestas. Duis luctus turpis at accumsan
                                    tincidunt. Phasellus risus risus, volutpat vel tellus ac, tincidunt fringilla massa.
                                    Etiam hendrerit dolor eget rutrum.</p>
                                <p class="overview"><b>Michael Holz</b> <span
                                        class="company-name">CEO, Media Analyst</span></p>
                            </div>
                        </div>
                        <!-- Carousel controls -->
                        <a class="carousel-control left carousel-control-prev prev" href="#myCarousel2"
                           data-slide="prev">
                            <i class="fa fa-angle-left"></i>
                        </a>
                        <a class="carousel-control right carousel-control-next next" href="#myCarousel2"
                           data-slide="next">
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--.testimonials-->
    <!--our-valuable-clients-->
    <section class="our-valuable-clients">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="heading-text text-center">
                        <h2>Our Valuable Clients</h2>
                        <p>Working with more that 100 clients from over 15 industry verticals</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 ">
                    <nav>
                        <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
                            <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home"
                               role="tab" aria-controls="nav-home" aria-selected="true">All Industries <span
                                    class="badge badge-light">29</span></a>
                            <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile"
                               role="tab" aria-controls="nav-profile" aria-selected="false">Agro</a>
                            <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact"
                               role="tab" aria-controls="nav-contact" aria-selected="false">Consumer</a>
                            <a class="nav-item nav-link" id="nav-about-tab" data-toggle="tab" href="#nav-about"
                               role="tab"
                               aria-controls="nav-about" aria-selected="false">Education</a>
                        </div>
                    </nav>
                    <div class="tab-content py-3 px-3 px-sm-0" id="nav-tabContent">
                        <div class="tab-pane fade show active" id="nav-home" role="tabpanel"
                             aria-labelledby="nav-home-tab">
                            <div class="row">
                                <div class="container my-4">
                                    <!--Carousel Wrapper-->
                                    <div id="multi-item-example-3" class="carousel slide carousel-multi-item"
                                         data-ride="carousel">

                                        <!--Controls-->
                                        <div class="controls-top">
                                            <a class="btn-floating prev" href="#multi-item-example-3" data-slide="prev"><i
                                                    class="fa fa-chevron-left"></i></a>
                                            <a class="btn-floating next" href="#multi-item-example-3" data-slide="next"><i
                                                    class="fa fa-chevron-right"></i></a>
                                        </div>
                                        <!--/.Controls-->

                                        <!--Indicators-->
                                        <ol class="carousel-indicators">
                                            <li data-target="#multi-item-example-3" data-slide-to="0"
                                                class="active"></li>
                                            <li data-target="#multi-item-example-3" data-slide-to="1"></li>
                                            <li data-target="#multi-item-example-3" data-slide-to="2"></li>
                                        </ol>
                                        <!--/.Indicators-->

                                        <!--Slides-->
                                        <div class="carousel-inner no-black" role="listbox">

                                            <!--First slide-->
                                            <div class="carousel-item active">

                                                <div class="row">
                                                    <div class="col-md-2">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                               src="<?=$block->getViewFileUrl("images/media/novo-nordisk.png");?>"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>

                                                    <div class="col-md-2 clearfix d-none d-md-block">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                               src="<?=$block->getViewFileUrl("images/media/acme.png");?>"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>

                                                    <div class="col-md-2 clearfix d-none d-md-block">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                              src="<?=$block->getViewFileUrl("images/media/healthcare.png");?>"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-md-2 clearfix d-none d-md-block">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                  src="<?=$block->getViewFileUrl("images/media/pharmasia.png");?>"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-md-2 clearfix d-none d-md-block">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                             src="<?=$block->getViewFileUrl("images/media/novo-nordisk.png");?>"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-md-2 clearfix d-none d-md-block">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="<?=$block->getViewFileUrl("images/media/brac.png");?>"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                            <!--/.First slide-->

                                            <!--Second slide-->
                                            <div class="carousel-item">

                                                <div class="row">
                                                    <div class="col-md-2">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                  src="<?=$block->getViewFileUrl("images/media/novo-nordisk.png");?>"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>

                                                    <div class="col-md-2 clearfix d-none d-md-block">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                  src="<?=$block->getViewFileUrl("images/media/acme.png");?>"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>

                                                    <div class="col-md-2 clearfix d-none d-md-block">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                               src="<?=$block->getViewFileUrl("images/media/healthcare.png");?>"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-md-2 clearfix d-none d-md-block">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="<?=$block->getViewFileUrl("images/media/pharmasia.png");?>"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-md-2 clearfix d-none d-md-block">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="<?=$block->getViewFileUrl("images/media/novo-nordisk.png");?>"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-md-2 clearfix d-none d-md-block">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                src="<?=$block->getViewFileUrl("images/media/brac.png");?>"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                            <!--/.Second slide-->

                                            <!--Third slide-->
                                            <div class="carousel-item">
                                                <div class="row">
                                                    <div class="col-md-2">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="<?=$block->getViewFileUrl("images/media/novo-nordisk.png");?>"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>

                                                    <div class="col-md-2 clearfix d-none d-md-block">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="<?=$block->getViewFileUrl("images/media/acme.png");?>"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>

                                                    <div class="col-md-2 clearfix d-none d-md-block">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                               src="<?=$block->getViewFileUrl("images/media/healthcare.png");?>"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-md-2 clearfix d-none d-md-block">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                               src="<?=$block->getViewFileUrl("images/media/pharmasia.png");?>"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-md-2 clearfix d-none d-md-block">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                   src="<?=$block->getViewFileUrl("images/media/novo-nordisk.png");?>"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-md-2 clearfix d-none d-md-block">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                               src="<?=$block->getViewFileUrl("images/media/brac.png");?>"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <!--/.Third slide-->
                                        </div>
                                        <!--/.Slides-->
                                    </div>
                                    <!--/.Carousel Wrapper-->
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                            Et et consectetur ipsum labore excepteur est proident excepteur ad velit occaecat qui minim
                            occaecat veniam. Fugiat veniam incididunt anim aliqua enim pariatur veniam sunt est aute sit
                            dolor anim. Velit non irure adipisicing aliqua ullamco irure incididunt irure non esse
                            consectetur nostrud minim non minim occaecat. Amet duis do nisi duis veniam non est eiusmod
                            tempor incididunt tempor dolor ipsum in qui sit. Exercitation mollit sit culpa nisi culpa
                            non
                            adipisicing reprehenderit do dolore. Duis reprehenderit occaecat anim ullamco ad duis
                            occaecat
                            ex.
                        </div>
                        <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
                            Et et consectetur ipsum labore excepteur est proident excepteur ad velit occaecat qui minim
                            occaecat veniam. Fugiat veniam incididunt anim aliqua enim pariatur veniam sunt est aute sit
                            dolor anim. Velit non irure adipisicing aliqua ullamco irure incididunt irure non esse
                            consectetur nostrud minim non minim occaecat. Amet duis do nisi duis veniam non est eiusmod
                            tempor incididunt tempor dolor ipsum in qui sit. Exercitation mollit sit culpa nisi culpa
                            non
                            adipisicing reprehenderit do dolore. Duis reprehenderit occaecat anim ullamco ad duis
                            occaecat
                            ex.
                        </div>
                        <div class="tab-pane fade" id="nav-about" role="tabpanel" aria-labelledby="nav-about-tab">
                            Et et consectetur ipsum labore excepteur est proident excepteur ad velit occaecat qui minim
                            occaecat veniam. Fugiat veniam incididunt anim aliqua enim pariatur veniam sunt est aute sit
                            dolor anim. Velit non irure adipisicing aliqua ullamco irure incididunt irure non esse
                            consectetur nostrud minim non minim occaecat. Amet duis do nisi duis veniam non est eiusmod
                            tempor incididunt tempor dolor ipsum in qui sit. Exercitation mollit sit culpa nisi culpa
                            non
                            adipisicing reprehenderit do dolore. Duis reprehenderit occaecat anim ullamco ad duis
                            occaecat
                            ex.
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
    <!--.our-valuable-clients-->
    <!--our-suppliers-->
    <section class="our-suppliers">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="heading-text text-center">
                        <h2>Our Suppliers</h2>
                        <p>Working with more that 30 suppliers from over 20 industry</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="container my-4">
                    <!--Carousel Wrapper-->
                    <div id="multi-item-example-2" class="carousel slide carousel-multi-item" data-ride="carousel">

                        <!--Controls-->
                        <div class="controls-top">
                            <a class="btn-floating prev" href="#multi-item-example-2" data-slide="prev"><i
                                    class="fa fa-chevron-left"></i></a>
                            <a class="btn-floating next" href="#multi-item-example-2" data-slide="next"><i
                                    class="fa fa-chevron-right"></i></a>
                        </div>
                        <!--/.Controls-->

                        <!--Indicators-->
                        <ol class="carousel-indicators">
                            <li data-target="#multi-item-example-2" data-slide-to="0" class="active"></li>
                            <li data-target="#multi-item-example-2" data-slide-to="1"></li>
                            <li data-target="#multi-item-example-2" data-slide-to="2"></li>
                        </ol>
                        <!--/.Indicators-->

                        <!--Slides-->
                        <div class="carousel-inner no-black" role="listbox">

                            <!--First slide-->
                            <div class="carousel-item active">
                                <div class="row">
                                    <div class="col-md-2">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                               src="<?=$block->getViewFileUrl("images/media/double-a.png");?>"
                                                 alt="Card image cap">
                                        </div>
                                    </div>

                                    <div class="col-md-2 clearfix d-none d-md-block">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                           src="<?=$block->getViewFileUrl("images/media/dell.png");?>"
                                                 alt="Card image cap">
                                        </div>
                                    </div>

                                    <div class="col-md-2 clearfix d-none d-md-block">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                               src="<?=$block->getViewFileUrl("images/media/tradeworth-group.png");?>"
                                                 alt="Card image cap">
                                        </div>
                                    </div>
                                    <div class="col-md-2 clearfix d-none d-md-block">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                src="<?=$block->getViewFileUrl("images/media/nestle.png");?>"
                                                 alt="Card image cap">
                                        </div>
                                    </div>

                                    <div class="col-md-2 clearfix d-none d-md-block">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                             src="<?=$block->getViewFileUrl("images/media/papertech.png");?>"
                                                 alt="Card image cap">
                                        </div>
                                    </div>
                                    <div class="col-md-2 clearfix d-none d-md-block">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                               src="<?=$block->getViewFileUrl("images/media/fresh.png");?>"
                                                 alt="Card image cap">
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <!--/.First slide-->
                            <!--Second slide-->
                            <div class="carousel-item">
                                <div class="row">
                                    <div class="col-md-2">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                               src="<?=$block->getViewFileUrl("images/media/double-a.png");?>"
                                                 alt="Card image cap">
                                        </div>
                                    </div>

                                    <div class="col-md-2 clearfix d-none d-md-block">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="<?=$block->getViewFileUrl("images/media/dell.png");?>"
                                                 alt="Card image cap">
                                        </div>
                                    </div>

                                    <div class="col-md-2 clearfix d-none d-md-block">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="<?=$block->getViewFileUrl("images/media/tradeworth-group.png");?>"
                                                 alt="Card image cap">
                                        </div>
                                    </div>
                                    <div class="col-md-2 clearfix d-none d-md-block">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                               src="<?=$block->getViewFileUrl("images/media/nestle.png");?>"
                                                 alt="Card image cap">
                                        </div>
                                    </div>

                                    <div class="col-md-2 clearfix d-none d-md-block">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                              src="<?=$block->getViewFileUrl("images/media/papertech.png");?>"
                                                 alt="Card image cap">
                                        </div>
                                    </div>
                                    <div class="col-md-2 clearfix d-none d-md-block">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                src="<?=$block->getViewFileUrl("images/media/fresh.png");?>"
                                                 alt="Card image cap">
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <!--/.Second slide-->

                            <!--Third slide-->
                            <div class="carousel-item">
                                <div class="row">
                                    <div class="col-md-2">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="<?=$block->getViewFileUrl("images/media/double-a.png");?>"
                                                 alt="Card image cap">
                                        </div>
                                    </div>

                                    <div class="col-md-2 clearfix d-none d-md-block">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                  src="<?=$block->getViewFileUrl("images/media/dell.png");?>"
                                                 alt="Card image cap">
                                        </div>
                                    </div>

                                    <div class="col-md-2 clearfix d-none d-md-block">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="<?=$block->getViewFileUrl("images/media/tradeworth-group.png");?>"
                                                 alt="Card image cap">
                                        </div>
                                    </div>
                                    <div class="col-md-2 clearfix d-none d-md-block">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="<?=$block->getViewFileUrl("images/media/nestle.png");?>"
                                                 alt="Card image cap">
                                        </div>
                                    </div>

                                    <div class="col-md-2 clearfix d-none d-md-block">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="<?=$block->getViewFileUrl("images/media/papertech.png");?>"
                                                 alt="Card image cap">
                                        </div>
                                    </div>
                                    <div class="col-md-2 clearfix d-none d-md-block">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                  src="<?=$block->getViewFileUrl("images/media/fresh.png");?>"
                                                 alt="Card image cap">
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <!--/.Third slide-->
                        </div>
                        <!--/.Slides-->
                    </div>
                    <!--/.Carousel Wrapper-->
                </div>
            </div>
        </div>
    </section>
    <!--.our-suppliers-->
</main>
<!--.main content-->
<!-- footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <ul class="list-group">
                    <li class="list-group-item active">About us</li>
                    <li class="list-group-item"><a href="#">About Gemsclip</a></li>
                    <li class="list-group-item"><a href="#">Gemsclip Team</a></li>
                    <li class="list-group-item"><a href="#">Career</a></li>
                    <li class="list-group-item"><a href="#">Contact Us</a></li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="list-group">
                    <li class="list-group-item active"><a href="#">Support</a></li>
                    <li class="list-group-item"><a href="#">Return Policy</a></li>
                    <li class="list-group-item"><a href="#">Credit Policy</a></li>
                    <li class="list-group-item"><a href="#">Terms & Conditions</a></li>
                    <li class="list-group-item"><a href="#">Privacy Policy</a></li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="list-group">
                    <li class="list-group-item active">MEDIA</li>
                    <li class="list-group-item"><a href="#">News</a></li>
                    <li class="list-group-item"><a href="#">Publications</a></li>
                    <li class="list-group-item active">Join Us On</li>
                    <li class="list-group-item">
                        <a href="#"><img   src="<?=$block->getViewFileUrl("images/media/fb-icon.png");?>"  alt="Facebook"></a>
                        <a href="#"><img  src="<?=$block->getViewFileUrl("images/media/twitter-icon.png");?>"  alt="twitter"></a>
                        <a href="#"><img   src="<?=$block->getViewFileUrl("images/media/linkedin-icon.png");?>"  alt="linkedin"></a>
                    </li>
                </ul>
            </div>
        </div>
        <hr class="featurette-divider">
        <p class="text-center">&copy; 2019 Gemsclip. All Rights Reserved.</p>
    </div>

</footer>
<!--.footer-->
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<!--<script src="pub/media/gemsclip/js/script.js"></script>-->
<!--<script src="js/script.js"></script>-->

<script type="text/javascript">
        $(document).ready(function(){
            $('[data-toggle="tooltip"]').tooltip();
        });
     </script>


</body>
</html>
