<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!-- 
AlPhaD UI - Header

* Version: 1.0
* Build Date    :  15-12-2017 
* Last Update   :  - []
* Author: ALPhA D
* Website: www.alphadsy.com
* contribute on github : https://github.com/alphadsy/alpha-ui
more ui & layout https://github.com/alphadsy
-->
 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>Header by AlPhaD</title>

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
<!-- font-awesome icons -->
<script defer src="https://use.fontawesome.com/releases/v5.0.1/js/all.js"></script>
<!-- header css -->
<link rel="stylesheet" href="pub/media/gemsclip/css/style-copy.css">
</head>
<body>

 
 

<!-- header #2 -->
<header class="header" id="header2">
    <div class="left">
        <div class="caption">
            <h2 class="title display-3">Header title</h2>
            <p class="text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum ea accusamus enim hic, itaque eius quibusdam maxime veritatis maiores, ipsum porro beatae. Quisquam deleniti maxime velit tempora, molestias corrupti iusto!</p>
            <div class="action input-group">
              <input type="text" class="form-control" placeholder="Search for..." required>
              <span class="input-group-btn">
                <button class="btn btn-success" type="button">Go!</button>
              </span>
        </div>
        </div>  
    </div>
    <i class="scroll fa fa-angle-double-down"></i>
</header>

<!-- header #3 -->

</body>
</html>
