<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 16px;
        color: #707070;
        padding: 3rem 0 0 !important;
    }
    footer {
        padding: 30px 0;
        background: #f5f5f5;
        background: url(<?=$block->getViewFileUrl("images/media/footer-bg.png");?>) center;
        background-size: cover;
    }

    .container {
        max-width: 1140px;
        margin: 0 auto;
    }
    .row {
        display: -ms-flexbox;
        display: flex;
        -ms-flex-wrap: wrap;
        flex-wrap: wrap;
        margin-right: -15px;
        margin-left: -15px;
    }
    .list-group {
        display: -ms-flexbox;
        display: flex;
        -ms-flex-direction: column;
        flex-direction: column;
        padding-left: 0;
        margin-bottom: 0;
    }
    footer li.list-group-item.active {
        color: #fff;
        background: transparent;
        border: transparent;
        text-transform: uppercase;
        padding: 10px 20px;
    }
    footer li.list-group-item {
        padding: 2px 20px;
        background: transparent;
        position: relative;
        display: block;
        margin-bottom: -1px;
        border: 0;
    }
    footer li.list-group-item a {
        color: #ccc;
        text-decoration: none;
        background-color: transparent;
    }
    footer li.list-group-item a:hover{
        text-decoration: underline;
    }
    .list-group-item:last-child {
        margin-bottom: 0;
        border-bottom-right-radius: .25rem;
        border-bottom-left-radius: .25rem;
    }
    .text-center {
        text-align: center!important;
    }
    footer .featurette-divider {
        margin: 20px 0;
        border-color:#707070;
    }
    @media (min-width: 768px){
        .col-md-4 {
            -ms-flex: 0 0 33.333333%;
            flex: 0 0 33.333333%;
            max-width: 33.333333%;
        }
    }

</style>
<body>
<!-- footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <ul class="list-group">
                    <li class="list-group-item active">About us</li>
                    <li class="list-group-item"><a href="#">About Gemsclip</a></li>
                    <li class="list-group-item"><a href="#">Gemsclip Team</a></li>
                    <li class="list-group-item"><a href="#">Career</a></li>
                    <li class="list-group-item"><a href="#">Contact Us</a></li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="list-group">
                    <li class="list-group-item active"><a href="#">Support</a></li>
                    <li class="list-group-item"><a href="#">Return Policy</a></li>
                    <li class="list-group-item"><a href="#">Credit Policy</a></li>
                    <li class="list-group-item"><a href="#">Terms & Conditions</a></li>
                    <li class="list-group-item"><a href="#">Privacy Policy</a></li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="list-group">
                    <li class="list-group-item active">MEDIA</li>
                    <li class="list-group-item"><a href="#">News</a></li>
                    <li class="list-group-item"><a href="#">Publications</a></li>
                    <li class="list-group-item active">Join Us On</li>
                    <li class="list-group-item">
                        <a href="#"><img   src="<?=$block->getViewFileUrl("images/media/fb-icon.png");?>"  alt="Facebook"></a>
                        <a href="#"><img  src="<?=$block->getViewFileUrl("images/media/twitter-icon.png");?>"  alt="twitter"></a>
                        <a href="#"><img   src="<?=$block->getViewFileUrl("images/media/linkedin-icon.png");?>"  alt="linkedin"></a>
                    </li>
                </ul>
            </div>
        </div>
        <hr class="featurette-divider">
        <p class="text-center">&copy; 2019 Gemsclip. All Rights Reserved.</p>
    </div>

</footer>
<!--.footer-->
</body>
</html>