<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="assets/css/carousel.css">
    <!--favicon-->
    <link rel="shortcut icon" href="assets/favicon.ico">
    <!--.favicon-->
    <!--font-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i,900,900i&display=swap"
          rel="stylesheet">
    <!--.font-->
    <!--font awesome -->
    <link href="pub/media/assets/css/all.css" rel="stylesheet">
    <!--.font awesome -->
    
    <!--common style-->
    <link rel="stylesheet" href="pub/media/assets/css/style.css">
    <!--.common style-->

    <title>Your everyday office needs | Gemsclip.com</title>
</head>
<body>
<!--header code goes here-->
<header>
    <nav class="navbar navbar-expand-md fixed-top bg-transparent display-none-on-phone">
        <a class="navbar-brand" href="#"><img src="pub/media/assets/img/logo.png" alt="logo"> </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <img src="pub/media/assets/img/mobile-menu-icon.png" alt="menu"/>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#"><i class="fas fa-envelope"></i>Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fas fa-user"></i>Login</a>
                </li>




                <?php if ($block->isLoggedIn()): ?>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo $block->getAccountUrl() ?>">
                        < ?php echo __('My Account') ?>
                        <i class="fas fa-user"></i>
                    </a>
                </li>
                <?php endif; ?>
 














                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="far fa-edit"></i>Become a member</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fas fa-shopping-cart"></i>Cart</a>
                </li>
            </ul>
        </div>
    </nav>
    <nav class="navbar navbar-expand-lg bg-transparent main-nav">
        <a class="navbar-brand display-block-on-phone" href="#"><img src="pub/media/assets/img/logo.png" alt="logo"> </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <div id="nav-icon0">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="display-block-on-phone">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#"><i class="fas fa-envelope"></i>Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="fas fa-user"></i>Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="far fa-edit"></i>Become a member</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="fas fa-shopping-cart"></i>Cart</a>
                    </li>
                </ul>
            </div>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Stationary
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Bags & Briefcases</a>
                        <a class="dropdown-item" href="#">Binders Files Folders</a>
                        <a class="dropdown-item" href="#">Desk
                            Organizers</a>
                        <a class="dropdown-item" href="#">Notebooks
                            and Diary</a>
                        <a class="dropdown-item"
                           href="#">Post-it & Sticky
                            Notes</a>
                        <a class="dropdown-item"
                           href="#">Stamps & Stamp
                            Pads</a>
                        <a class="dropdown-item"
                           href="#">Tape,
                            Fasteners & Adhesives</a>
                        <a class="dropdown-item" href="#">Writing
                            Supplies & Instruments</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Cleaning
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                        <a class="dropdown-item" href="#">Air
                            Fresheners And Deodorizers</a>
                        <a class="dropdown-item" href="#">Brooms,
                            Dustpans & Brushes</a>
                        <a class="dropdown-item" href="#">Dish
                            Soap & Detergent</a>
                        <a class="dropdown-item" href="#">First
                            Aid</a>
                        <a class="dropdown-item" href="#">Hard
                            Floor Care</a>
                        <a class="dropdown-item" href="#">Health
                            and Hygiene</a>
                        <a class="dropdown-item" href="#">Maintenance
                            Tools</a>
                        <a class="dropdown-item" href="#">Paper
                            Towels, Tissues & Dispensers</a>
                        <a class="dropdown-item" href="#">Safety
                            Supplies</a>
                        <a class="dropdown-item" href="#">Tools,
                            Parts & Supplies</a>
                        <a class="dropdown-item" href="#">Waste
                            Management & Recycling</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown3" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Pantry
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown3">
                        <a class="dropdown-item" href="#">All
                            Beverages</a>
                        <a class="dropdown-item" href="#">Chocolate
                            & Candy</a>
                        <a class="dropdown-item" href="#">Coffee &
                            Tea</a>
                        <a class="dropdown-item" href="#">Cookies
                            & Bars</a>
                        <a class="dropdown-item" href="#">Fruit
                            Snacks & Cups</a>
                        <a class="dropdown-item"
                           href="#">Juices</a>
                        <a class="dropdown-item" href="#">Nuts &
                            Seeds</a>
                        <a class="dropdown-item" href="#">Spreads
                            & Sweeteners</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown4" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        IT & Electronics
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown4">
                        <a class="dropdown-item"
                           href="#">Batteries &
                            Power</a>
                        <a class="dropdown-item"
                           href="#">Cell Phone
                            Accessories</a>
                        <a class="dropdown-item" href="#">Computer
                            Accessories</a>
                        <a class="dropdown-item" href="#">Computer
                            Monitors</a>
                        <a class="dropdown-item" href="#">Computer
                            Software</a>
                        <a class="dropdown-item" href="#">Computers</a>
                        <a class="dropdown-item"
                           href="#">GPS</a>
                        <a class="dropdown-item" href="#">Hard Drives & Data
                            Storage</a>
                        <a class="dropdown-item" href="#">Laptop & Laptop
                            Accessories</a>
                        <a class="dropdown-item" href="#">Networking &
                            WiFi</a>
                        <a class="dropdown-item" href="#">Office
                            Electronics</a>
                        <a class="dropdown-item"
                           href="#">Photocopiers</a>
                        <a class="dropdown-item" href="#">Printer and
                            Scanners</a>
                        <a class="dropdown-item" href="#">Shredders,
                            Projectors & Office Machines</a>
                        <a class="dropdown-item" href="#">Surveillance
                            & Security Cameras</a>
                        <a class="dropdown-item"
                           href="#">Toners &
                            Cartridges</a>
                        <a class="dropdown-item" href="#">Wearable
                            Technology</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="far fa-heart"></i>My Product</a>
                </li>
                 <li class="nav-item">
                     <button class="nav-link search-btn" onclick="mySearchFunction()"><i class="fas fa-search"></i>
                     </button>
                     <div id="searchDIV">
                         <!-- <form>
                             <div class="form-group">
                                 <input type="search" class="form-control" placeholder="Search">
                             </div>
                         </form> -->

                         <form method='get' action='http://127.0.0.1/magento2/catalogsearch/result/?'>
                          <input type="search" class="form-control" placeholder="Search" name='q'  formtarget="_blank" /> 
                          <!-- <button value='Seach'>Search</button> -->
                        </form>


                     </div>
                 </li>
                                         



            </ul>
        </div>
    </nav>
</header>
<!--.header code goes here-->
<!--main content-->
<a class="rfq-btn" href="/quickrfq/">Request a Quote</a>
<main role="main">
    <!--hero area-->
    <div class="hero-area">
        <div id="myCarousel" class="carousel slide carousel-fade" data-ride="carousel" data-interval="3000">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="pub/media/assets/img/slider-img-02.png" alt="Slider Image" background="#777" color="#777" text=" "
                         title=" "/>
                    <div class="container">
                        <div class="carousel-caption">
                            <h1>One-Stop Procurement Solution</h1>
                            <p>Can’t find an item you are looking for?<br>
                                Inform us to source it for you and we will do the rest.</p>
                            <p><a class="btn btn-lg btn-outline-success"
                                  href="http://www.gemsclip.com/computer-laptop.html" target="_blank" role="button">Learn
                                More</a></p>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="pub/media/assets/img/slider-img-05.png" alt="Slider Image" width="100%" height="100%"/>
                    <div class="container">
                        <div class="carousel-caption">
                            <h1>Save Up to 30% on Stationery Items</h1>
                            <p><a class="btn btn-lg btn-outline-success"
                                  href="http://www.gemsclip.com/stationary/other-products/tape-fasteners-mounting.html"
                                  target="_blank" role="button">Learn more</a></p>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="pub/media/assets/img/slider-img-01.png" alt="Slider Image" width="100%" height="100%"/>
                    <div class="container">
                        <div class="carousel-caption">
                            <h1>All kinds of Stationery Products</h1>
                            <p>Exclusive corporate distribution Partnership with "Papertech" & "Bashundhara"<br>
                                <!--    Inform us to source it for you and we will do the rest.</p> -->
                            <p><a class="btn btn-lg btn-outline-success"
                                  href="http://www.gemsclip.com/house-keeping/tissues-paper.html" target="_blank"
                                  role="button">Learn More</a></p>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="pub/media/assets/img/slider-img-03.png" alt="Slider Image" width="100%" height="100%"/>
                    <div class="container">
                        <div class="carousel-caption">
                            <h1>Worried about delivery?</h1>
                            <p>Relax just place your order we'll do the rest even if it has Multiple Locations<br>
                                <!-- Inform us to source it for you and we will do the rest.</p> -->
                            <p><a class="btn btn-lg btn-outline-success"
                                  href="http://www.gemsclip.com/house-keeping/canteen-item.html" target="_blank"
                                  role="button">Learn more</a></p>
                        </div>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <!--.hero area-->
    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->
    <!--how it works section-->
    <section class="how-it-works">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="heading-text text-center">
                        <h2>How It Works</h2>
                        <p>Learn how to use Gemsclip for buying your office needs!</p>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="embed-responsive embed-responsive-16by9">
                        <!-- <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/zpOULjyy-n8?rel=0"
                                allowfullscreen></iframe> -->
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/ctqtx4BR52g" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

                    </div>
                </div><!-- /.col-lg-4 -->
                <div class="col-lg-7">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <h5><span>01</span>Create an account</h5>
                            <p>Create an account to access your dashboard and manage your orders</p>
                        </li>
                        <li class="list-group-item">
                            <h5><span>02</span>Create your list</h5>
                            <p>Send your RFQ and add items to your list for easy order process</p>
                        </li>
                        <li class="list-group-item">
                            <h5><span>03</span>Place Order</h5>
                            <p>Place your order with customized delivery and billing information </p>
                        </li>
                        <li class="list-group-item">
                            <h5><span>04</span>Receive Delivery</h5>
                            <p>Receive order at your business location conveniently</p>
                        </li>
                    </ul>
                </div><!-- /.col-lg-4 -->
            </div><!-- /.row -->
        </div>
    </section>
    <!--.how it works section-->
    <!--Product Categories Section-->
    <section class="product-categories">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="heading-text text-center">
                        <h2>Product Categories</h2>
                        <p>Explore and list your desire products</p>
                    </div>
                </div>
                <div class="container my-4">
                    <!--Carousel Wrapper-->
                    <div id="multi-item-example" class="carousel slide carousel-multi-item" data-ride="carousel">

                        <!--Controls-->
                        <div class="controls-top">
                            <a class="btn-floating prev" href="#multi-item-example" data-slide="prev"><i
                                    class="fa fa-chevron-left"></i></a>
                            <a class="btn-floating next" href="#multi-item-example" data-slide="next"><i
                                    class="fa fa-chevron-right"></i></a>
                        </div>
                        <!--/.Controls-->

                        <!--Indicators-->
                        <ol class="carousel-indicators">
                            <li data-target="#multi-item-example" data-slide-to="0" class="active"></li>
                            <li data-target="#multi-item-example" data-slide-to="1"></li>
                        </ol>
                        <!--/.Indicators-->

                        <!--Slides-->
                        <div class="carousel-inner no-black" role="listbox">

                            <!--First slide-->
                            <div class="carousel-item active">

                                <div class="row">
                                    <div class="col-4 col-md-4">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="pub/media/assets/img/stationery.png" alt="Office Stationary"
                                                 alt="Card image cap">
                                            <div class="card-body">
                                                <p class="numberofitems">240 Items</p>
                                                <h4 class="card-title">Office Stationery</h4>

                                                <a href="http://www.gemsclip.com/stationary/other-products.html"
                                                   target="_blank" class="btn btn-view-all">View All</a>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-4 col-md-4 clearfix">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="pub/media/assets/img/cleaning.png" alt="Cleaning Stuff"
                                                 alt="Card image cap">
                                            <div class="card-body">
                                                <p class="numberofitems">400 Items</p>
                                                <h4 class="card-title">Cleaning Stuff</h4>

                                                <a href="#"
                                                   target="_blank" class="btn btn-view-all">View All</a>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-4 col-md-4 clearfix">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="pub/media/assets/img/safety.png" alt="Safety Equipment"
                                                 alt="Card image cap">
                                            <div class="card-body">
                                                <p class="numberofitems">200 Items</p>
                                                <h4 class="card-title">Safety Equipment</h4>

                                                <a href="#"
                                                   target="_blank" class="btn btn-view-all">View All</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <!--/.First slide-->

                            <!--Second slide-->
                            <div class="carousel-item">

                                <div class="row">
                                    <div class="col-4 col-md-4">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="pub/media/assets/img/electronics.png" alt="Office Stationary"
                                                 alt="Card image cap">
                                            <div class="card-body">
                                                <p class="numberofitems">240 Items</p>
                                                <h4 class="card-title">Electronics</h4>

                                                <a href="#"
                                                   target="_blank" class="btn btn-view-all">View All</a>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-4 col-md-4 clearfix">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="pub/media/assets/img/it.png" alt="Cleaning Stuff"
                                                 alt="Card image cap">
                                            <div class="card-body">
                                                <p class="numberofitems">400 Items</p>
                                                <h4 class="card-title">IT Equipments</h4>

                                                <a href="#" target="_blank"
                                                   class="btn btn-view-all">View All</a>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-4 col-md-4 clearfix">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="pub/media/assets/img/pantry.png" alt="Safety Equipment"
                                                 alt="Card image cap">
                                            <div class="card-body">
                                                <p class="numberofitems">200 Items</p>
                                                <h4 class="card-title">Pantry Items</h4>

                                                <a href="#"
                                                   target="_blank" class="btn btn-view-all">View All</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <!--/.Second slide-->

                        </div>
                        <!--/.Slides-->
                    </div>
                    <!--/.Carousel Wrapper-->
                </div>
            </div>
        </div>
    </section>
    <!--.Product Categories Section-->
    <!--Why Choose Us-->
    <section class="why-choose-us-section">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="heading-text text-center">
                        <h2>Why Choose Us</h2>
                        <p>Here are the reasons you can depend on Gemsclip</p>
                    </div>
                </div>
                <div class="col-3">
                    <div class="text-center">
                        <button type="button" class="btn tooltip-btn save-cost" data-toggle="tooltip" data-html="true"
                                title="Best way to minimize your additional cost of procurement  through us.">
                        </button>
                        <h5>Save Cost</h5>
                    </div>
                </div>
                <div class="col-3">
                    <div class="text-center">
                        <button type="button" class="btn tooltip-btn save-sourcing-time" data-toggle="tooltip"
                                data-html="true"
                                title="You don't have to bother about sourcing your desired products. Save time!">
                        </button>
                        <h5>Save Sourcing Time</h5>
                    </div>
                </div>
                <div class="col-3">
                    <div class="text-center">
                        <button type="button" class="btn tooltip-btn one-stop" data-toggle="tooltip" data-html="true"
                                title="Request for quotation, sample collection, on time  delivery, after sales service  - We do everything! Relax!">
                        </button>
                        <h5>One Stop<br/>
                            Procurement Solution</h5>
                    </div>
                </div>
                <div class="col-3">
                    <div class="text-center">
                        <button type="button" class="btn tooltip-btn location-delivery" data-toggle="tooltip"
                                data-html="true"
                                title="We'll deliver your goods at your doorsteps even if it is several locations against a single order. Isn't it amazing!">
                        </button>
                        <h5>On Location<br>
                            Delivery</h5>
                    </div>
                </div>
                <div class="col-3">
                    <div class="text-center">
                        <button type="button" class="btn tooltip-btn account-manager" data-toggle="tooltip"
                                data-html="true"
                                title="Think, a person of our team will dedicate for your company and when required basis however off course at our payroll!">
                        </button>
                        <h5>Key Account <br/>Manager</h5>
                    </div>
                </div>
                <div class="col-3">
                    <div class="text-center">
                        <button type="button" class="btn tooltip-btn procurement-analytics" data-toggle="tooltip"
                                data-html="true"
                                title="Project your next procurement budget with the the analytics of your past procurement information. Go one step ahead and keep rocking!">
                        </button>
                        <h5>Procurement<br>
                            Analytics</h5>
                    </div>
                </div>
                <div class="col-3">
                    <div class="text-center">
                        <button type="button" class="btn tooltip-btn authentic-products" data-toggle="tooltip"
                                data-html="true"
                                title="We never say that we deliver authentic products, rather we promise to deliver exactly what you want!">
                        </button>
                        <h5>Product<br>
                            Customization</h5>
                    </div>
                </div>
                <div class="col-3">
                    <div class="text-center">
                        <button type="button" class="btn tooltip-btn trusted-service" data-toggle="tooltip"
                                data-html="true"
                                title="We promise not to make your life in blundered.We respect your time and requirement.">
                        </button>
                        <h5>Trusted<br>
                            Service</h5>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--.Why Choose Us-->
    <!--testimonials-->
    <section class="testimonials">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="heading-text text-center">
                        <h2>Testimonials</h2>
                        <p>Some valuable words from our clients who are satisfied by our Services</p>
                    </div>
                    <div id="myCarousel2" class="carousel slide" data-ride="carousel">
                        <!-- Carousel indicators -->
                        <ol class="carousel-indicators">
                            <li data-target="#myCarousel2" data-slide-to="0" class="active"></li>
                            <li data-target="#myCarousel2" data-slide-to="1"></li>
                            <li data-target="#myCarousel2" data-slide-to="2"></li>
                        </ol>
                        <!-- Wrapper for carousel items -->
                        <div class="carousel-inner">
                            <div class="item carousel-item active">
                                <div class="img-box"><img src="pub/media/assets/img/yuichiro_ishii.png" alt=""></div>
                                <p class="testimonial">This is to certify that we have procured products from our
                                    trusted vendor, eGeneration B2B Ltd. (Gemsclip.com) on a monthly basis. The service
                                    and products supplied by them has been of exceptional quality & we’re very satisfied
                                    with the service provided.<br/>
                                    We confidently recommended eGeneration B2B Ltd. (Gemsclip.com) as a good procurement
                                    service provider & office supplies, IT equipment & electronic item supplier and
                                    expert in this field of business.
                                </p>
                                <p class="overview"><b>Yuichiro Ishii</b><span
                                        class="company-name">Managing Director & CEO, Bangladesh Honda Private Limited.</span>
                                </p>
                            </div>
                            <div class="item carousel-item">
                                <div class="img-box"><img src="pub/media/assets/img/sifullah_islam.png" alt=""></div>
                                <p class="testimonial">We confirmed that we have dealt with eGeneration B2B Ltd.
                                    (Gemsclip.com) since (30th May, 2017) during they have provided the business with
                                    excellent service, on time delivery and support in the area of procurement of Office
                                    Stationery Supplies, Cleaning Supplies, IT Equipment, Electrical & Electronic Items
                                    and many more.<br/>
                                    We confidently recommended eGeneration B2B Ltd. (Gemsclip.com) as a good procurement
                                    service provider & office supplies, IT equipment & electronic item supplier and
                                    expert in this field of business.
                                </p>
                                <p class="overview"><b>Md. Sifullah Islam</b> <span
                                        class="company-name">Former HR & Admin, Bagdoom.com</span></p>
                            </div>
                            <div class="item carousel-item">
                                <div class="img-box"><img src="pub/media/assets/img/masukul_alam.png" alt=""></div>
                                <p class="testimonial">I confirm that we have dealt with eGeneration B2B Ltd.
                                    (Gemsclip.com) since (04th September, 2018) during they have provided the business
                                    with excellent service, on time delivery and support in the area of procurement of
                                    <strong>Office Stationery Supplies, Cleaning Supplies, IT Equipment, Electrical &
                                        Electronic
                                        Items </strong>and many more.<br/>

                                    We confidently recommended eGeneration B2B Ltd. (Gemsclip.com) as a good procurement
                                    service provider & office supplies, IT equipment & electronic item supplier and
                                    expert in this field of business.
                                </p>
                                <p class="overview"><b>Mohammad Masukul Alam</b> <span
                                        class="company-name">Assistant Procurement Manager, Pathao Ltd.</span></p>
                            </div>
                        </div>
                        <!-- Carousel controls -->
                        <a class="carousel-control left carousel-control-prev prev" href="#myCarousel2"
                           data-slide="prev">
                            <i class="fa fa-angle-left"></i>
                        </a>
                        <a class="carousel-control right carousel-control-next next" href="#myCarousel2"
                           data-slide="next">
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--.testimonials-->
    <!--our-valuable-clients-->
    <section class="our-valuable-clients">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="heading-text text-center">
                        <h2>Our Valuable Clients</h2>
                        <p>Working with more than 100 clients from over 15 industry verticals</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12 ">
                    <nav>
                        <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
                            <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home"
                               role="tab" aria-controls="nav-home" aria-selected="true">All Industries <span
                                    class="badge badge-light">30</span></a>
                            <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile"
                               role="tab" aria-controls="nav-profile" aria-selected="false">Financial Institutes</a>
                            <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact"
                               role="tab" aria-controls="nav-contact" aria-selected="false">Healthcare Institutes</a>
                            <a class="nav-item nav-link" id="nav-about-tab" data-toggle="tab" href="#nav-about"
                               role="tab"
                               aria-controls="nav-about" aria-selected="false">Group of Companies</a>
                        </div>
                    </nav>
                    <div class="tab-content py-3 px-3 px-sm-0" id="nav-tabContent">
                        <div class="tab-pane fade show active" id="nav-home" role="tabpanel"
                             aria-labelledby="nav-home-tab">
                            <div class="row">
                                <div class="container my-4">
                                    <!--Carousel Wrapper-->
                                    <div id="multi-item-example-3" class="carousel slide carousel-multi-item"
                                         data-ride="carousel">

                                        <!--Controls-->
                                        <div class="controls-top">
                                            <a class="btn-floating prev" href="#multi-item-example-3" data-slide="prev"><i
                                                    class="fa fa-chevron-left"></i></a>
                                            <a class="btn-floating next" href="#multi-item-example-3" data-slide="next"><i
                                                    class="fa fa-chevron-right"></i></a>
                                        </div>
                                        <!--/.Controls-->

                                        <!--Indicators-->
                                        <ol class="carousel-indicators">
                                            <li data-target="#multi-item-example-3" data-slide-to="0"
                                                class="active"></li>
                                            <li data-target="#multi-item-example-3" data-slide-to="1"></li>
                                            <li data-target="#multi-item-example-3" data-slide-to="2"></li>
                                            <li data-target="#multi-item-example-3" data-slide-to="3"></li>
                                            <li data-target="#multi-item-example-3" data-slide-to="4"></li>
                                        </ol>
                                        <!--/.Indicators-->

                                        <!--Slides-->
                                        <div class="carousel-inner no-black" role="listbox">

                                            <!--First slide-->
                                            <div class="carousel-item active">

                                                <div class="row">
                                                    <div class="col-4 col-md-2">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/aamra.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>

                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/acme.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>

                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/adcomm.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/apex.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/bagdoom.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/bKash.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>

                                                </div>

                                            </div>
                                            <!--/.First slide-->

                                            <!--Second slide-->
                                            <div class="carousel-item">

                                                <div class="row">
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/bproperty.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/brac.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/brac-bank.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/community-bank.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/digicon.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/edison-group.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>

                                                </div>

                                            </div>
                                            <!--/.Second slide-->

                                            <!--Third slide-->
                                            <div class="carousel-item">
                                                <div class="row">
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/egeneration.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/fdl.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/grey.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/healthcare.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/honda.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/jmi-group.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <!--/.Third slide-->

                                            <!--Forth slide-->
                                            <div class="carousel-item">
                                                <div class="row">
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/marico.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/mi.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/nitol-niloy.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/novo-nordisk.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/padma-bank.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/pathao.png"
                                                                 alt="Card image cap">
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                            <!--/.Forth slide-->
                                            <!--Fifth slide-->
                                            <div class="carousel-item">
                                                <div class="row">

                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/saimon-group.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/standard-group.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/united-group.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/united-hospital.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/urmi-group.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/zuellig-pharma.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <!--/.Fifth slide-->
                                        </div>
                                        <!--/.Slides-->
                                    </div>
                                    <!--/.Carousel Wrapper-->
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                            <div class="row">
                                <div class="container my-4">
                                    <!--Carousel Wrapper-->
                                    <div id="multi-item-example-4" class="carousel slide carousel-multi-item"
                                         data-ride="carousel">
                                        <!--Slides-->
                                        <div class="carousel-inner no-black" role="listbox">
                                            <!--First slide-->
                                            <div class="carousel-item active">
                                                <div class="row">
                                                    <div class="col-4 col-md-2">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/brac-bank.png"
                                                                 alt="Card image cap">
                                                        </div>
                                                    </div>

                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/community-bank.png"
                                                                 alt="Card image cap">
                                                        </div>
                                                    </div>

                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/padma-bank.png"
                                                                 alt="Card image cap">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <!--/.First slide-->
                                        </div>
                                        <!--/.Slides-->
                                    </div>
                                    <!--/.Carousel Wrapper-->
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
                            <div class="row">
                                <div class="container my-4">
                                    <!--Carousel Wrapper-->
                                    <div id="multi-item-example-5" class="carousel slide carousel-multi-item"
                                         data-ride="carousel">
                                        <!--Slides-->
                                        <div class="carousel-inner no-black" role="listbox">
                                            <!--First slide-->
                                            <div class="carousel-item active">
                                                <div class="row">
                                                    <div class="col-4 col-md-2">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/acme.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>

                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/healthcare.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>

                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/novo-nordisk.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/zuellig-pharma.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/united-hospital.png"
                                                                 alt="Card image cap">
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                            <!--/.First slide-->
                                        </div>
                                        <!--/.Slides-->
                                    </div>
                                    <!--/.Carousel Wrapper-->
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="nav-about" role="tabpanel" aria-labelledby="nav-about-tab">
                            <div class="row">
                                <div class="container my-4">
                                    <!--Carousel Wrapper-->
                                    <div id="multi-item-example-6" class="carousel slide carousel-multi-item"
                                         data-ride="carousel">
                                        <!--Slides-->
                                        <div class="carousel-inner no-black" role="listbox">
                                            <!--First slide-->
                                            <div class="carousel-item active">
                                                <div class="row">
                                                    <div class="col-4 col-md-2">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/aamra.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>

                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/edison-group.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>

                                                    <div class="col-4 col-md-2 clearfix ">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/jmi-group.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/standard-group.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/united-group.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>
                                                    <div class="col-4 col-md-2 clearfix">
                                                        <div class="card mb-2">
                                                            <img class="card-img-top"
                                                                 src="pub/media/assets/img/clients-logo/urmi-group.png"
                                                                 alt="Card image cap">

                                                        </div>
                                                    </div>

                                                </div>

                                            </div>
                                            <!--/.First slide-->
                                        </div>
                                        <!--/.Slides-->
                                    </div>
                                    <!--/.Carousel Wrapper-->
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
    <!--.our-valuable-clients-->
    <!--our-suppliers-->
    <section class="our-suppliers">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="heading-text text-center">
                        <h2>Our Suppliers</h2>
                        <p>Working with more than 30 suppliers from over 20 industries </p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="container my-4">
                    <!--Carousel Wrapper-->
                    <div id="multi-item-example-2" class="carousel slide carousel-multi-item" data-ride="carousel">

                        <!--Controls-->
                        <div class="controls-top">
                            <a class="btn-floating prev" href="#multi-item-example-2" data-slide="prev"><i
                                    class="fa fa-chevron-left"></i></a>
                            <a class="btn-floating next" href="#multi-item-example-2" data-slide="next"><i
                                    class="fa fa-chevron-right"></i></a>
                        </div>
                        <!--/.Controls-->

                        <!--Indicators-->
                        <ol class="carousel-indicators">
                            <li data-target="#multi-item-example-2" data-slide-to="0" class="active"></li>
                            <li data-target="#multi-item-example-2" data-slide-to="1"></li>
                        </ol>
                        <!--/.Indicators-->

                        <!--Slides-->
                        <div class="carousel-inner no-black" role="listbox">

                            <!--First slide-->
                            <div class="carousel-item active">
                                <div class="row">
                                    <div class="col-4 col-md-2">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="pub/media/assets/img/suppliers-logo/supplier_double_a.png"
                                                 alt="Card image cap">
                                        </div>
                                    </div>

                                    <div class="col-4 col-md-2 clearfix">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="pub/media/assets/img/suppliers-logo/supplier_papertech.png"
                                                 alt="Card image cap">
                                        </div>
                                    </div>

                                    <div class="col-4 col-md-2 clearfix">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="pub/media/assets/img/suppliers-logo/supplier_bashundhara.png"
                                                 alt="Card image cap">
                                        </div>
                                    </div>
                                    <div class="col-4 col-md-2 clearfix">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="pub/media/assets/img/suppliers-logo/supplier_tradesworth.png"
                                                 alt="Card image cap">
                                        </div>
                                    </div>

                                    <div class="col-4 col-md-2 clearfix ">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="pub/media/assets/img/suppliers-logo/fresh.png"
                                                 alt="Card image cap">
                                        </div>
                                    </div>
                                    <div class="col-4 col-md-2 clearfix">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="pub/media/assets/img/suppliers-logo/supplier_dell.png"
                                                 alt="Card image cap">
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <!--/.First slide-->
                            <!--Second slide-->
                            <div class="carousel-item">
                                <div class="row">
                                    <div class="col-4 col-md-2">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="pub/media/assets/img/suppliers-logo/supplier_deli.png"
                                                 alt="Card image cap">
                                        </div>
                                    </div>

                                    <div class="col-4 col-md-2 clearfix">
                                        <div class="card mb-2">
                                            <img class="card-img-top"
                                                 src="pub/media/assets/img/suppliers-logo/supplier_nestle.png"
                                                 alt="Card image cap">
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <!--/.Second slide-->


                        </div>
                        <!--/.Slides-->
                    </div>
                    <!--/.Carousel Wrapper-->
                </div>
            </div>
        </div>
    </section>
    <!--.our-suppliers-->
</main>
<!--.main content-->
<!-- footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <ul class="list-group">
                    <li class="list-group-item active">About us</li>
                    <li class="list-group-item"><a href="/about-gemsclip">About Gemsclip</a></li>
                    <!-- <li class="list-group-item"><a href="#">Gemsclip Team</a></li> -->
                    <li class="list-group-item"><a href="/career-new">Career</a></li>
                    <li class="list-group-item"><a href="/contacts">Contact Us</a></li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="list-group">
                    <li class="list-group-item active"><a href="#">Support</a></li>
                    <li class="list-group-item"><a href="/return-policy">Return Policy</a></li>
                    <li class="list-group-item"><a href="/credit-policy">Credit Policy</a></li>
                    <li class="list-group-item"><a href="/terms-and-conditions">Terms & Conditions</a></li>
                    <li class="list-group-item"><a href="/privacy-policy">Privacy Policy</a></li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="list-group">
                    <li class="list-group-item active">MEDIA</li>
                    <!-- <li class="list-group-item"><a href="/publications">News</a></li> -->
                    <li class="list-group-item"><a href="/publications">Publications</a></li>
                    <li class="list-group-item active">Join Us On</li>
                    <li class="list-group-item">
                        <a href="https://www.facebook.com/gemsclip/" target="_blank"><img src="pub/media/assets/img/fb-icon.png"
                                                                                          alt="Facebook"></a>
                        <!--<a href="#"><img src="assets/img/twitter-icon.png" alt="twitter"></a>-->
                        <a href="https://www.linkedin.com/company/gemsclip" target="_blank"><img
                                src="pub/media/assets/img/linkedin-icon.png" alt="linkedin"></a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- Button trigger modal -->

        <hr class="featurette-divider">
        <p class="text-center">&copy; 2019 Gemsclip. All Rights Reserved.</p>
    </div>

</footer>
<!--.footer-->
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="pub/media/assets/js/script.js"></script>
</body>
</html>