
<head>
    <!-- Theme Made By www.w3schools.com - No Copyright -->
<!--    <meta charset="utf-8">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1">-->
<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">-->
<!--    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>-->
<!--    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>-->
    <style>


        .thumbnail {
            padding: 0 0 15px 0;
            border: none;
            border-radius: 0;
        }
        .thumbnail img {
            width: 100%;
            height: 100%;
            margin-bottom: 10px;
        }
        @media screen and (max-width: 768px) {
            .col-sm-4 {
                text-align: center;
                margin: 25px 0;
            }
        }
    </style>
</head>
<body>






<!-- Container (Portfolio Section) -->
<div class="container-fluid text-center bg-grey">

    <h2>What our customers say</h2>
    <div id="myCarousel" class="carousel slide text-center" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <div class="row text-center">
                    <div class="col-sm-4">
                        <div class="thumbnail">
                            <img src="pub/media/wysiwyg/band/paris.jpg" alt="Paris" width="400" height="300">
                            <p><strong>Paris</strong></p>
                            <p>Yes, we built Paris</p>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="thumbnail">
                            <img src="pub/media/wysiwyg/band/newyork.jpg" alt="Paris" width="400" height="300">
                            <p><strong>Paris</strong></p>
                            <p>Yes, we built Paris</p>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="thumbnail">
                            <img src="pub/media/wysiwyg/band/newyork.jpg" alt="Paris" width="400" height="300">
                            <p><strong>Paris</strong></p>
                            <p>Yes, we built Paris</p>
                        </div>
                    </div>


                </div>
            </div>
            <div class="item">

                    <div class="col-sm-4">
                        <div class="thumbnail">
                            <img src="pub/media/wysiwyg/band/newyork.jpg" alt="Paris" width="400" height="300">
                            <p><strong>Paris</strong></p>
                            <p>Yes, we built Paris</p>
                        </div>
                    </div>

                <div class="col-sm-4">
                    <div class="thumbnail">
                        <img src="pub/media/wysiwyg/band/newyork.jpg" alt="Paris" width="400" height="300">
                        <p><strong>Paris</strong></p>
                        <p>Yes, we built Paris</p>
                    </div>
                </div>

                <div class="col-sm-4">
                    <div class="thumbnail">
                        <img src="pub/media/wysiwyg/band/newyork.jpg" alt="Paris" width="400" height="300">
                        <p><strong>Paris</strong></p>
                        <p>Yes, we built Paris</p>
                    </div>
                </div>

            </div>
            <div class="item">

                    <div class="col-sm-4">
                        <div class="thumbnail">
                            <img src="pub/media/wysiwyg/band/sanfran.jpg" alt="Paris" width="400" height="300">
                            <p><strong>Paris</strong></p>
                            <p>Yes, we built Paris</p>
                        </div>
                    </div>

                <div class="col-sm-4">
                    <div class="thumbnail">
                        <img src="pub/media/wysiwyg/band/sanfran.jpg" alt="Paris" width="400" height="300">
                        <p><strong>Paris</strong></p>
                        <p>Yes, we built Paris</p>
                    </div>
                </div>

                <div class="col-sm-4">
                    <div class="thumbnail">
                        <img src="pub/media/wysiwyg/band/sanfran.jpg" alt="Paris" width="400" height="300">
                        <p><strong>Paris</strong></p>
                        <p>Yes, we built Paris</p>
                    </div>
                </div>


            </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

</body>




